### ISSUE TITLE
Chinese Simplified/Traditional Input Methods: No Autocompletion / Suggestions

### ISSUE THREAD

**Issue by ZhenhaoQi** [monkeytypegame/monkeytype#4673] opened 2023-09-27 06:28 UTC
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

zackqi

### Current Behavior

Multi-word Chinese Input doesn't work (character selection). You are unable to select phrases/words in general, when you type a multi-pinyin phrase. As you can see below, when I click space or any number to select the character recommendations, the caret simply skips to the next word and resets my characters. Also, if the number of pinyin characters exceeds the number of Chinese characters and the space, the character recommendations also reset. This makes typing in Chinese basically impossible on Monkeytype. Also, as an unrelated thing, although 2 word phrases are common in Chinese, it would be much more typing-test-ish to have either a single word, two word phrases, three word phrases, and idioms in general, to simulate typing an actual document.
![CleanShot 2023-09-26 at 23 18 20](https://github.com/monkeytypegame/monkeytype/assets/66653498/45e002a3-f0b4-4dd5-b61f-1b6bf604e825)

### Expected Behavior

When typing in the macOS Chinese - Simplified Pinyin Input Method, I should be able to select the character/phrase from the pinyin I type. 
![CleanShot 2023-09-26 at 23 25 41](https://github.com/monkeytypegame/monkeytype/assets/66653498/e0e38eb4-b170-42ec-8351-8223490922a7)

### Steps To Reproduce

Go to monkeytype.
Select any option prefixed with "Chinese" as your language.
Type in the Chinese - Pinyin input method.

### Environment

- OS: macOS Sonoma 14.0
- Browser: Arc Browser (Chromium Engine Version 117.0.5938.88)
- Browser Version: 1.9.2

**Comment by Miodec** [comment] 2023-09-29 13:06
Any chance you could add some sort of keyboard input overlay for both the current and intended behavior videos?

**Comment by ZhenhaoQi** [comment] 2023-09-29 18:26
I tried, but unfortunately, Cleanshot X (the screenshot/recording software I use), doesn't seem to pick up on the keystrokes. Sorry :(

**Comment by Miodec** [comment] 2023-10-02 11:46
Is this issue new in Sonoma? Or was it an issue in the previous version?

**Comment by ZhenhaoQi** [comment] 2023-10-02 18:00
I believe this was an issue in Ventura too. I think this problem directly correlates to how the macOS Input engine handles input fields and Chinese characters, which is messed up by monkeytype's formatting (?). I do not know if this is a problem on the Windows Chinese IME, but if I get access to a Windows system, I will test it.

**Comment by Miodec** [comment] 2023-10-03 11:51
This might be impossible to fix as for some reason the input system just adds random spaces when "contructing" the words???

**Comment by Miodec** [comment] 2023-10-03 11:55
Also, is this a duplicate of #4230 ?

**Comment by ZhenhaoQi** [comment] 2023-10-03 18:40
Oh wow, I am so sorry, I think it might be. The fix listed in the comment seems to be perfect, so it would be great if that was implemented! Sorry for the duplicate, I thought I searched thoroughly but I guess not.

**Comment by Miodec** [comment] 2023-10-06 11:09
Closing as duplicate then.

**Closed** 2023-10-06 11:09 UTC
Labels: bug, help wanted, stuck
