### ISSUE TITLE
Rework burst heatmap to not allow negative ranges

### ISSUE THREAD

**Issue by monkeytypegeorge** [monkeytypegame/monkeytype#4678] opened 2023-09-28 19:01 UTC
Currently, if there is a very slow and a very fast word in the history, its possible for the website to show weird ranges. Also things behave weirdly with very short tests, or tests where the speed is very consistent (which also means its hard to divide into 5 brackets). Easily testable with a 3 word test where 2 of them are slow.

**Comment by Miodec** [comment] 2023-09-28 19:04
<img width="468" alt="image" src="https://github.com/monkeytypegame/monkeytype/assets/13181393/bef6fa0f-3648-4153-8059-1c3ea6adc67b">

With burst wpms: 26, 49, 273

**Comment by Miodec** [comment] 2023-09-28 19:07
Probably should use median instead of mean

**Comment by sanidhyas3s** [comment] 2023-09-30 07:46
So the proposed fix is to not allow negative range and start from 0 or 1 wpm? Or some other fundamental changes?

**Comment by clarkWakeland** [comment] 2023-09-30 23:12
The issue is a result from the lower bound on the heatmap being median(burstlist) - step*1.5 , which produces a negative value if the mean deviation (step) is too large. My proposed change is to just start at 0 and increase by step * 0.5 each increment if the lower bound would otherwise be negative. 

Here's my result with burst wpms: 43, 36, 269
![image](https://github.com/monkeytypegame/monkeytype/assets/24725557/b7ac248b-0d4f-4179-a57d-cefd38aa5179)

Could I be assigned this issue?

**Comment by Miodec** [comment] 2023-10-02 11:37
> The issue is a result from the lower bound on the heatmap being median(burstlist) - step*1.5 , which produces a negative value if the mean deviation (step) is too large. My proposed change is to just start at 0 and increase by step * 0.5 each increment if the lower bound would otherwise be negative.
> 
> Here's my result with my changes for burst wpms: 43, 36, 269 ![image](https://user-images.githubusercontent.com/24725557/271798547-b7ac248b-0d4f-4179-a57d-cefd38aa5179.png)
> 
> Could I be assigned this issue?

This solution is close, but ideally i would like to avoid the first two brackets being essentially the same. Plus, the first bracket is "less than zero" which kidna makes no sense.

Ideally i would like the first bracket to be something like `< (a little bit over min speed)`, so for example if our min speed was 15, i would like the first bracket the be `< 24` (in this example, there is no relation between 15 and 24, just random numbers)

**Closed** 2023-10-27 13:51 UTC
