### ISSUE TITLE
Backend terminates with mongoservererror: ns not found while first time creating an account.

### ISSUE THREAD

**Issue by 2307vivek** [monkeytypegame/monkeytype#4440] opened 2023-07-07 20:26 UTC
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

No

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

No

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

2307vivek

### Current Behavior

After cloning the repository, and after going through all the setup including firebase and changing the `users.signUp` to `true` in 
 `backend\src\constants\base-configuration.ts`, the server terminates with `mongoservererror: ns not found` error while checking if the username exists while creating a new account. After restarting the server, everything works fine. A mongodb instance is running  and is connected to the backend.

### Expected Behavior

Checking for the username, if it exists or not should succeed.

### Steps To Reproduce

1. Ensure that you are starting from scratch.
2. Configure firebase
3. Database should be totally empty, only a `configurations` collection exists inside the monkeytype database.
4. Try to create a new account using email and password.
5. The backend will give mongoservererror: ns not found error.

### Environment

- OS: Windows 10
- Browser: Google Chrome
- Browser Version: 94.0.4606.71 (Official Build) (64-bit)

### Anything else?

This might help: https://stackoverflow.com/questions/72317353/why-does-mongodb-throw-error-ns-does-not-exist

**Comment by 2307vivek** [comment] 2023-07-07 20:30
The above is also true while saving a test result for the first time. The second time after restarting the server, it succeeds.

**Comment by Miodec** [comment] 2023-07-10 11:59
I just tried droppingthe `results` collection and i didn't get this error.

**Comment by 2307vivek** [comment] 2023-07-12 10:33
It is still happening with me. I will try to dig deeper into it.

**Comment by azazel-oss** [comment] 2023-07-16 04:06
I have also been receiving the same error that too multiple times. I cloned the project and ran it for the first time yesterday and got this error, I haven't been able to get to the root cause but I can confirm that the error is frequent (at least for the fresh clones)
<img width="1920" alt="Screenshot 2023-07-16 at 9 35 21 AM" src="https://github.com/monkeytypegame/monkeytype/assets/65448804/e0b1fa08-de16-46ce-a651-4a7dc48a6456">

**Comment by Miodec** [comment] 2023-07-17 10:42
When you run `npm list --depth=0` in the `backend` directory, whats the version of mongodb?

**Comment by azazel-oss** [comment] 2023-07-17 17:07
4.4.0

**Comment by Miodec** [comment] 2023-07-18 09:21
What about running `version()` inside the mongo shell?

**Comment by 2307vivek** [comment] 2023-07-18 11:04
`npm list --depth=0` : 4.4.0
`db.version()` : 6.0.6

**Comment by Miodec** [comment] 2023-07-18 11:06
Ah, its probably an error that comes from v6 then, im on v5.

**Comment by Miodec** [comment] 2023-07-18 14:07
Can you check if downgrading to version 5 fixes this? Actually its kinda weird that v5 handles creation of collections without any issues while v6 throws errors.

**Comment by azazel-oss** [comment] 2023-07-19 03:30
Downgrading to v5 didn't help in my case, I am still getting the same error. There is a recurring pattern, if I start the backend server and leave it idle, the error comes exactly 7 minutes after the api server starts listening on port 5005

**Comment by Miodec** [comment] 2023-07-21 11:04
Pushed a fix, should be ok now.

**Closed** 2023-07-21 11:04 UTC
Labels: bug, can't reproduce
