### ISSUE TITLE
Change show yesterday button to show today when viewing yesterdays daily leaderboards

### ISSUE THREAD

**Issue by jeffrey-zang** [monkeytypegame/monkeytype#3391] opened 2022-08-07 17:10 UTC
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

largank

### Current Behavior

When looking at yesterday's daily leaderboards, clicking "show yesterday" goes back to showing today
today:
![image](https://user-images.githubusercontent.com/66485719/183302628-d24d64f6-d71f-408c-b810-18d897283e50.png)
after clicking "show yesterday" (yesterday)
![image](https://user-images.githubusercontent.com/66485719/183302632-79c977eb-3ed1-421c-9ddb-d1b94894a471.png)
after clicking "show yesterday" again (today)
![image](https://user-images.githubusercontent.com/66485719/183302642-e0257bbd-a56e-410a-979b-2d338feb424b.png)

### Expected Behavior

Either it shows the day before yesterday, or it says "show today" after clicking on it

### Steps To Reproduce

1. go to "leaderboards"
2. go to "daily"
3. click "show yesterday"
4. click "show yesterday" again

### Environment

- OS: Windows 11
- Browser: Brave (chrome)
- Browser Version: 
![image](https://user-images.githubusercontent.com/66485719/183302770-b7f56470-549c-48d7-a4ac-4f001bf38523.png)

**Comment by Miodec** [comment] 2022-08-07 19:36
Not a bug - the button is a toggle. However for readability, well change the text on it and make it a normal button, not a toggle.

**Comment by sankalpmukim** [comment] 2022-08-13 08:39
I'm looking for a quick and easy contribution for onboarding and familiarity with the codebase... Can I get this assigned to me? 

I know it's not a high priority but would be nice to get it done still.

**Comment by anikait17a** [comment] 2022-08-19 12:10
can i solve this one
I am a beginner

**Closed** 2022-08-22 13:56 UTC
Labels: improvement
