### ISSUE TITLE
Punctuation beahavior for Caps Lock in native and layout emulator is different

### ISSUE THREAD

**Issue by farkon00** [monkeytypegame/monkeytype#4748] opened 2023-10-28 15:41 UTC
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

N/A

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

N/A

### Does the issue happen in incognito mode when logged out?

Yes

### Current Behavior

If you turn on qwerty emulator, then Caps Lock and try to type / it would type ?, which is different from native behavior.

### Expected Behavior

Have a list of keys/characters, which are considered punctuation, so they are not affected. 

### Steps To Reproduce

1. Turn on qwerty emulator
2. Press caps lock
3. Press /

### Environment

- OS: Fedora 37
- Browser: Firefox
- Browser Version: 117.0 (64-bit)

### Anything else?

This was introduced by [4d2a8f3](https://github.com/monkeytypegame/monkeytype/commit/4d2a8f31809de038f31fa54d51d734ec4565557e)

**Comment by Miodec** [comment] 2023-10-30 11:54
Duplicate of #4743

**Closed by Miodec** 2023-10-30 11:54 UTC
Labels: bug
