### ISSUE TITLE
the caret is malfunctioning after a recent commit

### ISSUE THREAD

**Issue by shivaji43** [monkeytypegame/monkeytype#5693] opened 2024-07-31 09:49 UTC
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Steps To Reproduce

https://github.com/user-attachments/assets/15a41283-b26b-4310-a7c6-720d10dd3f0e

### Environment

- OS:
- Browser:
- Browser Version:

**Comment by rizwanmustafa** [comment] 2024-07-31 13:00
I have not ben able to reproduce this. Can you try it in `Incognito Mode` or `Private Windows`. Also please share your settings by exporting them from the menu. Thanks

**Comment by rizwanmustafa** [comment] 2024-07-31 13:31
It is because of `tape mode`

**Comment by Miodec** [comment] 2024-07-31 13:44
Should be fixed already

**Comment by Miodec** [comment] 2024-07-31 13:50
Check again, just pushed.

**Closed** 2024-07-31 14:30 UTC
Labels: bug
