### ISSUE TITLE
"Report quote" doesn't work

### ISSUE THREAD

**Issue by achtchaern** [monkeytypegame/monkeytype#3916] opened 2023-01-14 17:01 UTC
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

No

### Account name

achtchaern

### Account config

{"theme":"serika_dark","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#2c2e31","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":true,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":true,"quickRestart":"off","punctuation":false,"numbers":false,"words":25,"time":15,"mode":"quote","quoteLength":[2],"language":"swiss_german","fontSize":1.5,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":true,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":false,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":false,"playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"125","chartAccuracy":false,"chartStyle":"scatter","minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","alwaysShowCPM":false,"ads":"off","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"showLiveAcc":false,"showLiveBurst":false,"monkey":false,"repeatQuotes":"typing","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":false,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off"}

### Current Behavior

After typing a quote, there is an option to report the typed quote. After filling out the report form and clicking on "Report" (to post it), an error message appears, asking me to "please select a quote"
![MonkeyType](https://user-images.githubusercontent.com/47472995/212485146-7a137c33-1494-4940-80c4-e6644331d356.png)

### Expected Behavior

I'd expect that the report is being sent since there is definitely a quote selected (the one I've just typed)

### Steps To Reproduce

- Go to quote mode
- Type a quote
- Click on the flag icon in the "Source" section of the end screen
- Fill out the form and click "report"

### Environment

- OS: Windows 10 22H2
- Browser: Chromium
- Browser Version: 109

**Comment by Miodec** [comment] 2023-01-16 21:32
Can't reproduce. Does it happen consistently for you?

**Comment by achtchaern** [comment] 2023-01-16 23:32
I think I know why. I'm Swiss which is why I only type "swiss german" quotes. Those are not native but derived from the regular German quotes, with just the character "ß" replaced with "ss". So I guess when reporting a quote when having "swiss german" selected, the app is not able to source the original quote.

See #3699

**Comment by Miodec** [comment] 2023-01-17 11:21
Closed by 287234f430d4f536295008ab48c4cd493d778041

**Closed by Miodec** 2023-01-17 11:21 UTC
Labels: bug, waiting for update, can't reproduce
