### ISSUE TITLE
auto fill form of edge browser

### ISSUE THREAD

**Issue by venkat2305** [monkeytypegame/monkeytype#3437] opened 2022-08-25 13:15 UTC
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

venkat2305

### Current Behavior

auto fill form of the edge browser keeps coming when trying to type its really annoying

### Steps To Reproduce

just type on the website in edge browser

### Environment

- OS: windows
- Browser: edge
- Browser Version: latest

### Anything else?

no

**Comment by Miodec** [comment] 2022-08-26 10:01
Duplicate of #3362

**Closed by Miodec** 2022-08-26 10:01 UTC
Labels: bug
