### ISSUE TITLE
"Save screenshot" doesn't render word history colors correctly

### ISSUE THREAD

**Issue by danielrparks** [monkeytypegame/monkeytype#3931] opened 2023-01-21 16:00 UTC
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

dvorakp

### Current Behavior

When I use the screenshot button with input history + burst heatmap enabled, colors 1 and 3 render the same as 0 and 5 in the screenshot.

### Expected Behavior

Colors 1 and 3 should be visually distinguishable from 0 and 5.

### Steps To Reproduce

1. Complete a typing test
2. Click on `Toggle words history`
3. Click on `Toggle burst heatmap` if the heatmap is not already enabled
4. Click `Save screenshot`

### Environment

- OS: Arch Linux
- Browser: Firefox
- Browser Version: 109.0 (arch linux build 109.0-1)

### Anything else?

Screenshot taken with Monkeytype's button:
![screenshot](https://user-images.githubusercontent.com/42898924/213875321-4aee5d33-98bf-441d-b307-82f726a6d4f9.png)

Screenshot taken with Firefox's built-in screenshot feature:
![screenshot](https://user-images.githubusercontent.com/42898924/213875298-ddda353c-5a25-4d71-b675-79a3793ad571.png)

**Comment by Miodec** [comment] 2023-01-21 17:23
Duplicate of #1613

**Closed by Miodec** 2023-01-21 17:23 UTC
Labels: bug
