### ISSUE TITLE
Tests never saved and error: Test invalid - inconsistent test duration 

### ISSUE THREAD

**Issue by gonsen71** [monkeytypegame/monkeytype#5401] opened 2024-05-15 18:23 UTC
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

No

### Does the issue happen in incognito mode when logged in?

Yes

### Does the issue happen in incognito mode when logged out?

No

### Account name

gonsen1

### Account config

{"theme":"catppuccin","themeLight":"serika","themeDark":"serika_dark","autoSwitchTheme":false,"customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#2c2e31","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":["catppuccin"],"showKeyTips":true,"smoothCaret":"medium","quickRestart":"off","punctuation":false,"numbers":false,"words":100,"time":300,"mode":"words","quoteLength":[1],"language":"english_1k","fontSize":2,"freedomMode":false,"difficulty":"normal","blindMode":false,"quickEnd":false,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":"off","timerStyle":"mini","liveSpeedStyle":"off","liveAccStyle":"off","liveBurstStyle":"off","colorfulMode":false,"randomTheme":"off","timerColor":"main","timerOpacity":"1","stopOnError":"off","showAllLines":false,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"overrideSync","keymapShowTopRow":"layout","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":true,"singleListCommandLine":"manual","capsLockWarning":true,"playSoundOnError":"off","playSoundOnClick":"off","soundVolume":"0.5","startGraphsAtZero":true,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"accountChart":["on","on","on","on"],"minWpm":"off","minWpmCustomSpeed":100,"highlightMode":"letter","typingSpeedUnit":"wpm","ads":"result","hideExtraLetters":false,"strictSpace":false,"minAcc":"off","minAccCustom":90,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"off","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off","minBurst":"off","minBurstCustomSpeed":100,"burstHeatmap":true,"britishEnglish":false,"lazyMode":false,"showAverage":"off","tapeMode":"off","maxLineWidth":70}

### Current Behavior

I always do the 1k english 100 words test. Recently when I finish a pop up appears saying '**Test invalid - inconsistent test duration** and my test is not saved'. According to the site this started happening on 5 May or after, because none of the tests I've done since then have been saved.

### Expected Behavior

I expect my tests to be saved. 

### Environment

- OS: Linux
- Browser: Firefox ESR
- Browser Version: 115.10.0esr (64-bit)

### Anything else?

Looking on github could be due to 80e0af7 or e9a83d5, but maybe is something else. 

I have also tested it on Chromium incognito and I have the same issue.

I also tested _time_ and _quote_, it happens the same also.

Thanks.

**Comment by gonsen71** [comment] 2024-05-21 07:06
Yes, as I said already I also tried on Chromium apart from Firefox. 

Maybe you missed this part:

> ### Anything else?
> 
> Looking on github could be due to 80e0af7 or e9a83d5, but maybe is something else.
> 
> I have also tested it on Chromium incognito and I have the same issue.

Anyways, on incognito I only had one extension enabled on both Firefox and Chromium. I tried today without any extensions on both browsers on incognito, and didn't work at first. Then I tried smaller tests like **10 words** and **15 seconds**, and started working on both browsers, but it was a hit and miss (I mean with this that sometimes it worked sometimes it didn't). Then I enabled the extensions and then I tried on Firefox NOT Incognito with extensions, and it also worked hit and miss. So in the end, what it matters is the kind of test, I suspect the longer the test the higher the probability to not work and to not be saved.

Thank you!

**Comment by PHPirates** [comment] 2024-05-25 10:17
I just saw the error "Test invalid - inconsistent test duration" as well, but it was only once so far and I cannot reproduce. Using Windows.
![image](https://github.com/monkeytypegame/monkeytype/assets/15669080/83643834-6004-41ea-9e81-3c7c11c4355b)

![Untitled](https://github.com/monkeytypegame/monkeytype/assets/15669080/452e0926-003d-49b0-b2af-b4f9b3167c5d)

**Comment by gonsen71** [comment] 2024-05-26 07:05
> Are you modifying anything relating to time / date in your system?

No I don't, but javascript is not very reliable for that. For example, if you compress or extract a big file, or you compile some software (all cores involved) while doing a test I think is very probable you'll hit this error.

I wasn't compiling anything though. I will try later the test with only the browser open, only one tab and nothing else.

> I just saw the error "Test invalid - inconsistent test duration" as well, but it was only once so far and I cannot reproduce. Using Windows.

Could you try a longer test? like 50 or 100 words? I think it might be easier to hit this error.

**Comment by Ottaviocr** [comment] 2024-05-26 09:09
I have just had the exact issue. I landed to this page after googling the error. I didn't capture the screenshot. I can post more details if needed. This is the first time it happens to me, but I only use MT every now and again.

**Comment by MightyGamesDan** [comment] 2024-06-20 22:15
This happens to me most times after I skip (click the restart button) on a test shortly after starting it. E.g. when I mess up early in a test and want to start fresh. I noticed this happen when I had autofail at 95% on, because it would stop the test if I messed up on the first few characters.
Browser: Chrome on Mac, with AdBlock

**Comment by MAdrianMattocks** [comment] 2024-07-10 14:15
I'm getting this now too.
Browser: Edge on Windows. Adblock is off.

**Comment by zal-ua** [comment] 2024-07-16 06:43
I have the same issue. I am doing 10 min custom test once aper per day, and it's the third time that Monkeytype doesn't save the result because of this error. I have no clue what I should do to resolve this issue.

**Comment by Miodec** [comment] 2024-07-16 08:39
Added a log when this error occurs. Can you guys check the console and let me know what numbers you get? 
![image](https://github.com/user-attachments/assets/5d01f4cf-080a-4a25-863f-90880e96065a)

**Comment by tokudayo** [comment] 2024-07-17 04:56
@Miodec I have been getting more of these recently, here is the log of what happened just now

<img width="318" alt="inconsistent log" src="https://github.com/user-attachments/assets/fd132539-39bd-43f2-b9b3-1e4d555a9990">

**Comment by MAdrianMattocks** [comment] 2024-07-17 12:23
@Miodec Got it again. Attached is the full console. Line 4415 is where your log line is.
[monkeytype.com-1721218829347.log](https://github.com/user-attachments/files/16265446/monkeytype.com-1721218829347.log)
Edge on Windows 10

**Comment by kizzull** [comment] 2024-07-17 20:07
I get this error constantly, it is super annoying. Seems to throw this error whenever I get a decent score, as if to troll me.

**Comment by Miodec** [comment] 2024-07-17 20:40
I made the check less strict. Bit of a dirty fix but im not sure what to do right now.

**Comment by 4itor** [comment] 2024-10-14 06:49
When it happens, it happens a lot; 5 times in a row today.
Finally googled the error and arrived here.
Will try to get console output next, this is super annoying when it appears.

**Comment by everman32** [comment] 2024-11-02 11:14
This happens with me on my second computer with Windows 7, Chrome with uBlock Origin.
![Безымянный](https://github.com/user-attachments/assets/e42bc88f-beee-485d-8d7f-4948f32d7b06)
![image](https://github.com/user-attachments/assets/de484d18-aae0-4ca4-b708-52eb62230414)

**Comment by bensums** [comment] 2024-11-29 10:20
Just got this as well. Really annoying. Daily 10-minute test down the drain. Isn't the fix here to save but marked as invalid, rather than not save? Then we can just filter for valid/invalid/etc as needed. I personally don't care if my tests are "valid" or not, whatever that means (and I imagine most people also don't care, but could be wrong).

**Comment by bensums** [comment] 2024-11-29 10:22
Looking at the code, you could just save `ce.testDuration` and `dateDur` as two properties of the saved test.

**Comment by zal-ua** [comment] 2024-12-03 06:47
I am also having 10-minute exercises and I found that by going to the
stats, then going back to the test and reloading the page helps me avoid
the "not valid" issue at the end of the test.

**Comment by Miodec** [comment] 2024-12-11 10:06
When you guys get this issue again, on the result page, could you press esc, search for `copy result stats`, press enter, then send the data here or to `contact@monkeytype.com`

**Comment by bensums** [comment] 2024-12-11 11:43
Will do, but why not just save the test anyway? Can always filter them out later if needed. It's a really annoying experience to just lose the test due to some consideration you don't even care about.

**Comment by everman32** [comment] 2024-12-14 10:52
@Miodec

{"lastResult":{"wpm":27.28,"rawWpm":46.47,"charStats":[54,5,0,1],"charTotal":92,"acc":90.22,"mode":"words","mode2":"10","punctuation":true,"numbers":true,"lazyMode":false,"timestamp":1734173537816,"language":"english_450k","restartCount":1,"incompleteTests":[{"acc":64.71,"seconds":9.41}],"incompleteTestSeconds":9.41,"difficulty":"normal","blindMode":false,"tags":[],"keySpacing":[290.7,257.9,67.5,95.1,228.4,129.7,257.9,130.2,162.1,96.2,132.1,163.3,161,289.2,383.5,104.4,122.2,230,258.4,98,289.9,288.3,97,226.7,415.6,43.7,197,97.4,97.2,767.1,204.1,96.6,195.4,669.4,732.7,512,381.8,383.8,351.8,163.6,257,161.5,162.5,34.3,226.5,71.5,189.3,64,323.4,257,542.5,161,775.3,193.6,446.9,225.3,226.2,382.7,64.8,132.4,320.5,198.6,924,98.4,64.4,198.3,129.9,447.3,130.1,194,764.7,135.2,125.6,415.3,225.8,1084.3,226.9,764.5,130.5,194.1,129.6,130.1,133.1,269.7,198.6,257.4,224.9,353.6,257.1,96.1,164.5],"keyDuration":[102.39999999990687,35.199999999953434,99.5,131.5,132.60000000009313,66.10000000009313,66.79999999981374,97.39999999990687,97.69999999995343,104,100.19999999995343,68.5,97.4000000001397,98.20000000018626,97.69999999995343,98.19999999995343,131.5,132.4000000001397,64.10000000009313,65.89999999990687,66.5999999998603,34.199999999953434,130.39999999990687,67.39999999990687,121.89999999990687,78.79999999981374,100.69999999995343,105.0999999998603,134.30000000004657,70.30000000004657,76.19999999995343,104.39999999990687,69.69999999995343,66.19999999995343,66.60000000009313,66.30000000004657,96.10000000009313,129.5,97.69999999995343,66.0999999998603,98,97.80000000004657,98.30000000004657,67.5,98.89999999990687,69.69999999995343,94,99.19999999995343,71.0999999998603,99.60000000009313,67.9000000001397,65.69999999995343,68.4000000001397,161.10000000009313,66.19999999995343,66.19999999995343,129.5,97,74.60000000009313,68.5,66.4000000001397,71.20000000018626,98.10000000009313,66.5,99.5,70.80000000004657,97.89999999990687,66.60000000009313,137.69999999995343,130.4000000001397,97.9000000001397,130,132.5,99.70000000018626,131.30000000004657,97.30000000004657,65.5999999998603,97.69999999995343,66.10000000009313,68.4000000001397,65.69999999995343,66.4000000001397,101,97.39999999990687,97.80000000004657,97.9000000001397,65.80000000004657,99.5,129.5,105.4000000001397,68.69999999995343,4.800000000046566],"keyOverlap":343.7,"lastKeyToEnd":4.8,"startToFirstKey":0,"consistency":59.59,"wpmConsistency":55.33,"keyConsistency":23.86,"funbox":"none","bailedOut":false,"chartData":{"wpm":[0,0,60,45,60,50,43,37,33,34,32,38,35,33,30,28,27,25,24,23,22,25,25,27],"raw":[72,72,60,60,48,48,48,12,36,36,84,36,24,48,48,24,60,36,48,12,24,72,48,63],"err":[0,0,0,0,0,1,1,1,1,0,0,0,0,0,1,2,0,1,0,1,0,0,0,0]},"testDuration":23.76,"afkDuration":0,"stopOnLetter":false},"start":355523.0000000001,"end":379278.20000000007,"start3":1734173513390,"end3":1734173537798,"afkHistory":[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],"errorHistory":[{"count":0,"words":[0,0,0,0,0,0]},{"count":0,"words":[0,0,0,0,0,0]},{"count":0,"words":[0,0,1,1,1]},{"count":0,"words":[1,1,1,1,1]},{"count":0,"words":[1,1,2,2]},{"count":1,"words":[2,2,2,2]},{"count":1,"words":[2,2,2,3]},{"count":1,"words":[3]},{"count":1,"words":[3,3,4]},{"count":0,"words":[4,4,4]},{"count":0,"words":[5,5,5,5,5,5,5]},{"count":0,"words":[5,5,6]},{"count":0,"words":[6,6]},{"count":0,"words":[6,6,6,6]},{"count":1,"words":[6,6,6,6]},{"count":2,"words":[6,7]},{"count":0,"words":[7,7,7,7,7]},{"count":1,"words":[7,7,7]},{"count":0,"words":[7,7,7,7]},{"count":1,"words":[8]},{"count":0,"words":[8,8]},{"count":0,"words":[8,8,8,8,8,8]},{"count":0,"words":[9,9,9,9]},{"count":0,"words":[9,9,9,9]}],"wpmHistory":[0,0,60,45,60,50,43,37,33,34,32,38,35,33,30,28,27,25,24,23,22,25,25,27],"rawHistory":[72,72,68,66,62,60,58,52,51,49,52,51,49,49,49,47,48,47,47,46,45,46,46,46],"burstHistory":[68,63,57,22,47,72,42,49,49,61],"keypressCountHistory":[6,6,5,5,4,4,4,1,3,3,7,3,2,4,4,2,5,3,4,1,2,6,4,4],"currentBurstStart":377925.4,"lastSecondNotRound":true,"missedWords":{"878":2,"dondaine":2,"otiorhynchid":3,"blackwaters.":2},"accuracy":{"correct":83,"incorrect":9},"keypressTimings":{"spacing":{"first":355519.70000000007,"last":379273.4,"array":[290.7,257.9,67.5,95.1,228.4,129.7,257.9,130.2,162.1,96.2,132.1,163.3,161,289.2,383.5,104.4,122.2,230,258.4,98,289.9,288.3,97,226.7,415.6,43.7,197,97.4,97.2,767.1,204.1,96.6,195.4,669.4,732.7,512,381.8,383.8,351.8,163.6,257,161.5,162.5,34.3,226.5,71.5,189.3,64,323.4,257,542.5,161,775.3,193.6,446.9,225.3,226.2,382.7,64.8,132.4,320.5,198.6,924,98.4,64.4,198.3,129.9,447.3,130.1,194,764.7,135.2,125.6,415.3,225.8,1084.3,226.9,764.5,130.5,194.1,129.6,130.1,133.1,269.7,198.6,257.4,224.9,353.6,257.1,96.1,164.5],"average":261.0296703296701,"sd":204.05577103110832},"duration":{"array":[102.39999999990687,35.199999999953434,99.5,131.5,132.60000000009313,66.10000000009313,66.79999999981374,97.39999999990687,97.69999999995343,104,100.19999999995343,68.5,97.4000000001397,98.20000000018626,97.69999999995343,98.19999999995343,131.5,132.4000000001397,64.10000000009313,65.89999999990687,66.5999999998603,34.199999999953434,130.39999999990687,67.39999999990687,121.89999999990687,78.79999999981374,100.69999999995343,105.0999999998603,134.30000000004657,70.30000000004657,76.19999999995343,104.39999999990687,69.69999999995343,66.19999999995343,66.60000000009313,66.30000000004657,96.10000000009313,129.5,97.69999999995343,66.0999999998603,98,97.80000000004657,98.30000000004657,67.5,98.89999999990687,69.69999999995343,94,99.19999999995343,71.0999999998603,99.60000000009313,67.9000000001397,65.69999999995343,68.4000000001397,161.10000000009313,66.19999999995343,66.19999999995343,129.5,97,74.60000000009313,68.5,66.4000000001397,71.20000000018626,98.10000000009313,66.5,99.5,70.80000000004657,97.89999999990687,66.60000000009313,137.69999999995343,130.4000000001397,97.9000000001397,130,132.5,99.70000000018626,131.30000000004657,97.30000000004657,65.5999999998603,97.69999999995343,66.10000000009313,68.4000000001397,65.69999999995343,66.4000000001397,101,97.39999999990687,97.80000000004657,97.9000000001397,65.80000000004657,99.5,129.5,105.4000000001397,68.69999999995343,4.800000000046566],"average":90.07065217392064,"sd":26.59643053054927}},"keyOverlap":{"total":343.69999999995343,"lastStartTime":-1},"wordsHistory":["Hypersonically","agalwoods","dondaine","878","911","overing;","otiorhynchid","blackwaters.","Weakfish","exacta."],"inputHistory":["Hypersonically","agalwoods","dondsine","978","911","overing;","otiorhyncid","blackwarers.","Weakfish","exacta."]}

**Comment by bensums** [comment] 2024-12-21 10:34
@Miodec
[result_stats.json](https://github.com/user-attachments/files/18218164/result_stats.json)

**Closed** 2024-12-23 15:16 UTC
Labels: bug, waiting for update, can't reproduce
