### ISSUE TITLE
Search doesn't work on phones.

### ISSUE THREAD

**Issue by Shashwat-pd** [monkeytypegame/monkeytype#3293] opened 2022-07-02 14:08 UTC
### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does the issue happen when logged in?

Yes

### Does the issue happen when logged out?

Yes

### Does the issue happen in incognito mode when logged in?

No

### Does the issue happen in incognito mode when logged out?

Yes

### Account name

shashwat-pd

### Current Behavior

When I try to change language from the button above the prompt on the phone, the search functionality doesn't filter the list according to the entered keywords. However, the phone version from the chrome developer tools works fine.

### Expected Behavior

The list has to be filtered with the state of the input box (works on PC). or has to have a search button that when clicked, shows only the entered language in the dropdown.

### Steps To Reproduce

1. Go to 'monkeytype.com' on the mobile version of chrome.
2. Click on the change language button above the prompt.
3. Type in any language.

### Environment

- OS: Windows 11
- Browser: Google Chrome
- Browser Version: 103.0.5060.66

**Comment by Miodec** [comment] 2022-07-02 14:27
Android or iOS?

**Comment by Shashwat-pd** [comment] 2022-07-02 14:47
Android

**Comment by Miodec** [comment] 2022-07-02 14:50
Already known. 

Duplicate of #2361

**Closed by Miodec** 2022-07-02 14:50 UTC
Labels: bug
